name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remova essa linha se for publicar o pacote

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3  # Adicionando a dependência do provider
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
